import pyautogui as auto



def ir_pesquisa():
    auto.press("tab")
    auto.press("tab")
    auto.press("tab")
    auto.press("tab")

def ir_selecionar():
    auto.press("tab")
    auto.press("tab")
    auto.press("tab")
    auto.press("tab")
    auto.press("tab")
    auto.press("tab")
    auto.press("tab")
    auto.press("tab")
    auto.press("tab")
    auto.press("tab")
    auto.press("tab")
    auto.press("tab")
    auto.press("tab")
    auto.press("tab")
    auto.press("tab")
    auto.press("tab")
    auto.press("tab")
    auto.press("tab")
    auto.press("tab")
    auto.press("tab")
    auto.press("tab")
    auto.press("tab")
    auto.press("tab")
    auto.press("tab")
    auto.press("tab")
    auto.press("tab")
    auto.press("tab")
    auto.press("tab")
    auto.press("tab")
    auto.press("tab")
    auto.press("tab")
    auto.press("tab")
    auto.press("tab")
    auto.press("tab")
    auto.press("tab")
    auto.press("tab")
    auto.press("tab")
    auto.press("tab")
    auto.press("tab")
    auto.press("tab")
    auto.press("tab")
    auto.press("tab")
    auto.press("tab")
    auto.press("tab")
    auto.press("tab")
    auto.press("tab")
    auto.press("tab")
    auto.press("tab")
    auto.press("tab")
    auto.press("tab")
    auto.press("tab")
    auto.press("tab")
    auto.press("tab")
    auto.press("tab")
    auto.press("tab")
    auto.press("tab")
    auto.press("tab")
    auto.press("tab")
    auto.press("tab")
    auto.press("tab")
    auto.press("tab")
    auto.press("tab")



def main():
    auto.PAUSE = 0.60
    auto.press("win")
    auto.write("firefox")
    auto.press("enter")
    auto.write("youtube.com.br")
    auto.press("enter")
    auto.sleep(2)
    ir_pesquisa()                               
    auto.write("Autentic Games Minecraft policia e ladrão")
    auto.press("enter")
    ir_selecionar()
    auto.press("enter")


if __name__ == "__main__":
    main()